const paragraphs = [
    "Ibu Tiara pintar memasak rendang, yaitu makanan terkenal khas daerah asalnya, Sumatra Barat. Contoh makanan khas Sumatra Barat lainnya adalah sate padang, nasi kapau, ayam pop, gulai itiak, dan dendeng balado. Makanan khas daerah merupakan salah satu contoh keragaman budaya di Indonesia. ",
    "Tarian daerah memiliki keunikan gerakan yang menjadi ciri khas suatu wilayah di Indonesia. Tarian juga merupakan identitas suatu daerah, seperti tari Kipas Pakarena dari Sulawesi Selatan. Tari ini ditampilkan oleh sekelompok penari dengan gerakan yang seragam dan serasi. ",
    "Menjalin hubungan pertemanan dengan semua orang tanpa membeda-bedakan merupakan sikap terpuji. Memiliki teman yang berasal dari daerah yang berbeda dapat menambah wawasan kita. Kita dapat mengetahui adat istiadat, keunikan, makanan khas, dan bahasa yang dimiliki oleh daerah lain. ",
    "Kekayaan budaya bangsa tercermin dari beragamnya karakteristik pakaian adat dan rumah adat. Keragaman tersebut menjadi simbol pariwisata yang banyak menarik perhatian wisatawan asing dan domestik. TMII (Taman Mini Indonesia Indah) adalah contoh tempat wisata yang menampilkan miniatur rumah adat dan pakaian adat di Indonesia. ",
    "Agar lebih paham kembali mengenai paragraf deduktif dan bentuknya, berikut disajikan beberapa contoh paragraf deduktif dikutip dari buku Bahasa Indonesia SMA Kelas XI oleh Sri Sutarni dkk, buku Paragraf Bahasa Indonesia oleh Oldrie Ch Sorey dari Kemdikbud, dan buku Terampil Menulis Paragraf oleh Asul Wiyanto.",
    "Cristiano Ronaldo merupakan salah satu pesepak bola terbaik di abad 21. Sepanjang karirnya, Cristiano Ronaldo mampu meraih prestasi-prestasi tertinggi di dunia sepak bola. Selama lebih dari dua dekade, Ronaldo telah membela empat tim yang berbeda, yaitu Sporting CP, Manchester United, Real Madrid, dan Juventus. Dari keempat tim itu, pemain berusia 37 tahun itu mampu memberikan gelar ke semua tim yang ia bela. Total sudah ada 34 trofi yang didapat oleh Ronaldo bersama empat tim tersebut.",
    "Bulan April ini petani di Grobogan mengalami gagal panen. Hal ini disebabkan cuaca yang sangat tidak menentu. Selain itu hama wereng juga mengganggu pertumbuhan padi. Curah hujan yang sangat tinggi membuat sawah petani banjir akibatnya tanaman padi yang masih pendek menjadi tergenang dan membusuk. Kanal yang dibuat di sekitar sawah petani juga mengalami penyumbatan, sehingga area persawahan mengalami kebanjiran di mana-mana.",


"Banyak sekali penyakit yang dihadapi peternak unggas, dari yang paling enteng sampai yang membuat kerugian besar. Jenis umum seperti cacingan, tela, snot, mencret, cacar, dan sebagainya sudah biasa menyerang unggas kita. Seluruh penyakit tadi ada obatnya dan bisa dibeli di poultry shop. Juga caranya mengobati beraneka macam, disuntik, diteteskan atau dicampurkan dengan makanannya.",

"Brokoli termasuk sayuran dengan kandungan antioksidan tinggi sehingga cara memasaknya harus benar. Usahakan agar teksturnya matang, tetapi jangan sampai mengurangi atau menghabiskan kandungan gizinya. Sayuran ini lebih tepat dimasak jenis rebus setengah matang sebelum dikonsumsi. Segera tiriskan dan siram dengan air dingin agar tetap berwarna cantik dan bentuknya tidak hancur. Cara memotongnya juga harus benar yaitu mengikuti tangkainya.",

"Semangat serta kesungguhan hati guru dalam mengajar dirasakan semakin pudar karena kesejahteraan terabaikan. Imbalan yang mereka terima rendah. Gaji mereka sering terlambat dan banyak potongan untuk keperluan yang kadang-kadang tidak jelas. Mereka juga tidak memiliki status sosial ekonomi yang bergengsi.",

"Kegiatan seorang penulis dapat disamakan dengan seorang petani yang mencangkul sawah ladangnya. Pak tani akan bertenaga kalau cukup makan dan minum. Bila kurang makan dan minum, ia akan cepat merasa lelah, letih, dan loyo. Demikian pula seorang penulis. Bila penulis sedikit membaca, kurang melakukan riset untuk bahan tulisnya, dan tidak sensitif terhadap lingkungannya, tentu saja ia akan kehabisan ide.",
"Guru menguasai materi dengan baik. Siswa terkelola dalam suasana pembelajaran yang kondusif. Proses pembelajaran aktif dan partisipatif. Evaluasi dilaksanakan sebagai pengukuran tingkat penyerapan siswa. Hal-hal tersebut merupakan indikasi menuju keberhasilan pembelajaran di kelas.",
"Indonesia merupakan Negara yang kaya akan Sumber daya alam. Contohnya di Pulau Sumatera terdiri dari suku batak, suku minang , suku aceh, suku melayu dan lain-lain sebagainya yang masing-masing memiliki kebudayaan yang berbeda-beda. Tidak hanya di Pulau Sumatera saja, bahkan di Pulau Jawa juga terdapat Suku Jawa, Sunda, Betawi, Badui, dan suku-suku lainya. Kalimantan, Sulawesi, Maluku, Bali Papua, dan pulau-pulau lainnya juga terdapat bermacam-macam suku dengan kebudayaannya masing-masing.",
"Indonesia diklaim sebagai negara dengan kepulauan terbesar yang ada di dunia. Sebab, menurut penelitian, pulau di Indonesia mencapai lebih dari 17.000. Jumlah itu disebut-sebut menjadi yang terbanyak di dunia. Di antara 17.000 pulau itu, 7.000 di antaranya pulau di Indonesia ini berpenghuni. Pulau-pulau itu tersebar di 38 Provinsi.",
"Ketika depresi, orang itu akan merasa kehilangan semangat dan gairah hidup. Wajahnya tampak sedih, kusut, dan cahaya rupanya kosong. Biasanya jika berjalan kakinya diseret dan menimbulkan suara yang tidak enak di telinga. Selain itu dia merasa takut dan cemas menghadapi hari-hari berikutnya. Dirinya merasa mempunyai kesalahan yang banyak dan besar. Di mana saja merasa tidak betah."
];